"""Add status and error_message to documents

Revision ID: 2c137022172a
Revises: 2fc5771fc58a
Create Date: 2026-02-14 15:31:09.415434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2c137022172a'
down_revision: Union[str, Sequence[str], None] = '2fc5771fc58a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus'), nullable=False))
    op.add_column('documents', sa.Column('error_message', sa.Text(), nullable=True))
    op.alter_column('documents', 'content_text',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294967295),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'content_text',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(),
               nullable=False)
    op.drop_column('documents', 'error_message')
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###
