"""Add question_type to items table

Revision ID: d3692cb95d7d
Revises: 1bbcef677522
Create Date: 2026-03-22 16:34:21.163312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd3692cb95d7d'
down_revision: Union[str, Sequence[str], None] = '1bbcef677522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'content_text',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294967295),
               existing_nullable=True)
    op.add_column('items', sa.Column('question_type', sa.Enum('MCQ', 'TF', 'OPEN', 'MATCHING', 'CALCULATED', 'MIXED', name='questiontype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'question_type')
    op.alter_column('documents', 'content_text',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
