"""Add multitype question counts

Revision ID: 1bbcef677522
Revises: b5d17e127763
Create Date: 2026-03-22 16:32:56.129944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1bbcef677522'
down_revision: Union[str, Sequence[str], None] = 'b5d17e127763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'content_text',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294967295),
               existing_nullable=True)
    op.add_column('generation_configs', sa.Column('num_mcq', sa.Integer(), nullable=False))
    op.add_column('generation_configs', sa.Column('num_matching', sa.Integer(), nullable=False))
    op.add_column('generation_configs', sa.Column('num_calculated', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_configs', 'num_calculated')
    op.drop_column('generation_configs', 'num_matching')
    op.drop_column('generation_configs', 'num_mcq')
    op.alter_column('documents', 'content_text',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
