"""Add is_complex to documents

Revision ID: b5d17e127763
Revises: c2d3e4f5a6b7
Create Date: 2026-03-22 13:32:59.615761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b5d17e127763'
down_revision: Union[str, Sequence[str], None] = 'c2d3e4f5a6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage_logs')
    op.drop_constraint(op.f('fk_subjects_program'), 'curriculum_subjects', type_='foreignkey')
    op.create_foreign_key(None, 'curriculum_subjects', 'programs', ['program_id'], ['id'])
    op.drop_constraint(op.f('fk_topics_materia'), 'curriculum_topics', type_='foreignkey')
    op.create_foreign_key(None, 'curriculum_topics', 'curriculum_subjects', ['materia_id'], ['id'])
    op.add_column('documents', sa.Column('is_complex', sa.Boolean(), server_default='0', nullable=False))
    op.alter_column('documents', 'content_text',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294967295),
               existing_nullable=True)
    op.alter_column('documents', 'uploaded_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('exports', 'exported_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('generation_configs', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('fk_gen_document'), 'generation_configs', type_='foreignkey')
    op.create_foreign_key(None, 'generation_configs', 'documents', ['document_id'], ['id'])
    op.alter_column('items', 'is_validated',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('items', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('fk_items_config'), 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'generation_configs', ['config_id'], ['id'])
    op.alter_column('logs', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('options', 'is_correct',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_constraint(op.f('fk_options_item'), 'options', type_='foreignkey')
    op.create_foreign_key(None, 'options', 'items', ['item_id'], ['id'])
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.drop_constraint(None, 'options', type_='foreignkey')
    op.create_foreign_key(op.f('fk_options_item'), 'options', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.alter_column('options', 'is_correct',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('logs', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key(op.f('fk_items_config'), 'items', 'generation_configs', ['config_id'], ['id'], ondelete='CASCADE')
    op.alter_column('items', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('items', 'is_validated',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_constraint(None, 'generation_configs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_gen_document'), 'generation_configs', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.alter_column('generation_configs', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('exports', 'exported_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('documents', 'uploaded_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('documents', 'content_text',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.drop_column('documents', 'is_complex')
    op.drop_constraint(None, 'curriculum_topics', type_='foreignkey')
    op.create_foreign_key(op.f('fk_topics_materia'), 'curriculum_topics', 'curriculum_subjects', ['materia_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'curriculum_subjects', type_='foreignkey')
    op.create_foreign_key(op.f('fk_subjects_program'), 'curriculum_subjects', 'programs', ['program_id'], ['id'], ondelete='CASCADE')
    op.create_table('usage_logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('model_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('input_tokens', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('output_tokens', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_tokens', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('usage_logs_ibfk_1'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
